### ISSUE TITLE
Compilation fails on Windows with VS 2019

### ISSUE THREAD

**Issue by Aculeo** [FourPi/Xam.Plugin.Mixpanel.iOS#1]
First of all, thanks for this, that made it rather easy to get bindings for the latest MixPanel framework. But I do have a rather weird issue: My project compiles on Mac with VS 2019, and it compiles on Windows with VS 2017. But it fails on Windows with VS 2019 with the following:

```
The referenced component 'Mixpanel.framework' could not be found.
```	
There's also this warning, which may or may not be relevant..

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Windows.After.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.ObjCBinding.Common.After.props (19,2)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\Code\CSBG_CommunityOfSpecialistsMobileApp\src\App\Bindings\Mixpanel.iOS\Mixpanel.iOS.csproj]	
```

Have you, by any chance, seen this error as well? It certainly does sound more like a VS/Xamarin bug though.

**Comment by beeradmoore** [comment]
I have not seen that error before, although I am using VS for Mac. I know someone at work is using VS 2019 on windows so I'll double check with them next week to see if they have come across this yet.

Is the windows machine with 2017 and windows machine with 2019 the same machine? Do any other binding libraries cause this issue?

**Comment by Aculeo** [comment]
VS 2017 and 2019 are on the same computer, both up to date. And this is the only binding library in the project. I will try recreating the library from scratch as well..

**Comment by beeradmoore** [comment]
@Aculeo , we are not using this internally at the moment so I can't let you know if we are experiencing this issue or not. Did the issue go away by any chance?

**Comment by Aculeo** [comment]
I think it's been fixed: https://developercommunity.visualstudio.com/content/problem/571350/xamarin-ios-binding-refernce-wont-build-anymore.html?childToView=598294#comment-598294

But so far I've switched back to VS 2017 for development, but thanks for checking!
