### ISSUE TITLE
Upgrade Mixpanel to 3.5.0?

### ISSUE THREAD

**Issue by TingtingAn** [FourPi/Xam.Plugin.Mixpanel.iOS#3]
Hi, is it possbile to upgrade Mixpanel nuget to 3.5.0?

**Comment by beeradmoore** [comment]
I think you mean 3.5.0?
I have an internal build we are testing with those updates. If they go good Ill bring them into this repo and push out a nuget in the next 24-48 hours.

**Comment by beeradmoore** [comment]
I also have that in testing :)

**Comment by beeradmoore** [comment]
Update on this, Android testing isn't going well. Project doesn't seem to find the namespace, but if I extract the dll from the NuGet Package and add it manually it works. Still investigating that.
Wanting to double check your PR with re-doing objective sharpie to see if all bindings are found but my local cocoaods (or objective sharpie) does not want to work. 

I'll keep you updated and let you know when the nuget is ready.

**Comment by TingtingAn** [comment]
It looks fine on my mac with your latest android source code.  
![Screen Shot 2019-10-31 at 11 08 21 AM](https://user-images.githubusercontent.com/8109811/67916330-4cb1c980-fbd0-11e9-8b8c-308ced7ae5f3.png)


Do you want I give you the nupkg file?

And are there some issues on iOS plugin also？

**Comment by beeradmoore** [comment]
Oh, interesting... 
For me the Xam.Plugin.Mixpanel namespace isn't found. This is part the reason why I am going to format and re-install. My dev environment has gone bonkers.

I just want to verify with both iOS and Android that there are no new APIs added. I think from your PR there was one new one.

I tried to re-bind the iOS build with objective sharpie but that gave me all sorts of errors. As above, things are broken here. Time to format.

**Comment by beeradmoore** [comment]
3.5.0 nuget was released. Thanks for your PR!
Android code is commited for 5.6.5, however I am going to look into reducing its 136 build warnings before I do a nuget release of it.

**Comment by beeradmoore** [comment]
@TingtingAn , Android package has been sent off to nuget.org
